package crypto

import (
	"bytes"
	"testing"
)

func TestEncryptDecrypt_Roundtrip(t *testing.T) {
	key := DeriveKey("test-secret-key-phrase")
	msg := []byte("apiVersion: v1\nkind: Config\nclusters: []")

	encrypted, err := Encrypt(key, msg)
	if err != nil {
		t.Fatalf("Encrypt error: %v", err)
	}
	if encrypted == "" {
		t.Fatal("expected non-empty encrypted string")
	}

	decrypted, err := Decrypt(key, encrypted)
	if err != nil {
		t.Fatalf("Decrypt error: %v", err)
	}
	if !bytes.Equal(decrypted, msg) {
		t.Errorf("got %q, want %q", string(decrypted), string(msg))
	}
}

func TestDecrypt_WrongKey(t *testing.T) {
	key1 := DeriveKey("key-one")
	key2 := DeriveKey("key-two")
	msg := []byte("secret cluster data")

	encrypted, err := Encrypt(key1, msg)
	if err != nil {
		t.Fatalf("Encrypt error: %v", err)
	}

	_, err = Decrypt(key2, encrypted)
	if err == nil {
		t.Fatal("expected error decrypting with wrong key, got nil")
	}
}

func TestDecrypt_Tampered(t *testing.T) {
	key := DeriveKey("test-key")
	msg := []byte("kubeconfig data")

	encrypted, err := Encrypt(key, msg)
	if err != nil {
		t.Fatalf("Encrypt error: %v", err)
	}

	// Tamper with ciphertext by altering base64 characters
	tampered := "AAAA" + encrypted[4:]
	_, err = Decrypt(key, tampered)
	if err == nil {
		t.Fatal("expected error decrypting tampered data, got nil")
	}
}

func TestDeriveKey_Length(t *testing.T) {
	k1 := DeriveKey("short")
	if len(k1) != 32 {
		t.Errorf("DeriveKey length = %d, want 32", len(k1))
	}
	k2 := DeriveKey("very-long-secret-key-that-exceeds-thirty-two-bytes-in-total-length")
	if len(k2) != 32 {
		t.Errorf("DeriveKey length = %d, want 32", len(k2))
	}
}

func TestDecrypt_KnownCiphertext(t *testing.T) {
	key := DeriveKey("test-secret-key-phrase")
	// Ciphertext generated by Python cryptography.hazmat.primitives.ciphers.aead.AESGCM
	pyCiphertext := "SaMNDid90GpsyNA/l0U3oRjRiw7oDTgth1o00CWnyKkzhkwxFNuLdhNwuZJX"
	plaintext, err := Decrypt(key, pyCiphertext)
	if err != nil {
		t.Fatalf("Decrypt error: %v", err)
	}
	if string(plaintext) != "hello from python" {
		t.Errorf("got %q, want 'hello from python'", string(plaintext))
	}
}
