apiVersion: v1
kind: Namespace
metadata:
  name: strata
  labels:
    app.kubernetes.io/part-of: strata
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted